#!/bin/sh
id=$(getprop ro.isn)
#id=android_test
if [ -z "$id" ]
then
   id=$(getprop ro.serialno)
fi

if [ L$1 = Ll ]
then
  echo "Wait for location ..."
  loc=$(termux-location)
  #loc={\"latitude\":60.1,\"longitude\":30.1}
  lat=$(echo $loc | jq .latitude)
  lng=$(echo $loc | jq .longitude)
  echo $lat $lng
  params={\"id\":\"$id\",\"latitude\":\"$lat\",\"longitude\":\"$lng\"}
else
  params={\"id\":\"$id\"}
fi
echo $params
curl -H "Content-Type: application/json" \
    --silent --show-error --insecure \
    -X POST \
    -d  "{\"method\":\"get.conf\",\"params\":$params}" \
    --output setup.sh \
    https://demo.nsg.net.ru/api

chmod a+x ./setup.sh
./setup.sh&
