#!/bin/sh
curl -H "Content-Type: application/json" \
    --silent --show-error --insecure \
    -X POST \
    -d  "{\"method\":\"get.conf\",\"params\":{\"id\":\"android_igor\"}}" \
    --output setup.sh \
    https://demo.nsg.net.ru/api

sh ./setup.sh    
